### PR TITLE
first pr ;))))))))))))

### PR DESCRIPTION
**Pull request by lewisakura**
pl0x merge i spent loads of my precious time on this

### CODE REVIEW

**Comment by ghost** [comment]
you pushed to `master` and not `dev`

**Comment by lewisakura** [comment]
that's the point

it's a readme change

i was making it look nicer

**Comment by ghost** [comment]
the readme is different in `dev`

**Comment by lewisakura** [comment]
shit.

**Comment by lewisakura** [comment]
2 minutes.

**Pull request closed without merging**
